baseURL: /
languageCode: en
title: Platform UI

enableRobotsTXT: true
disableAliases: true
markup:
  goldmark:
    renderer:
      unsafe: true
  tableOfContents:
    startLevel: 2
    endLevel: 2
    ordered: false
  highlight:
    codeFences: true
    guessSyntax: false
    hl_Lines: ""
    lineNoStart: 1
    lineNos: false
    lineNumbersInTable: true
    noClasses: true
    style: dracula
    tabWidth: 2

taxonomies:
  category: category
  tags: tags

summaryLength: 30

menu:
  main:
  - identifier: docs
    name: Docs
    url: /docs/getting-started/
    weight: 1
  - identifier: icons
    name: Icons
    url: /icons/
    weight: 2
  - identifier: launchpad
    name: Launchpad
    url: /launchpad/components

params:
  gtmID: 
  rim: Ritter Insurance Marketing
  rim_url: https://ritterim.com
  rimdev: RIMdev  
  rimdev_url: https://rimdev.io 
